import './global.css'
import { Inter } from 'next/font/google'
import { Layout } from '@/components'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter', })

export const metadata = {
  title: 'Movie App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans`}>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  )
}
